# Generated by Django 5.1.4 on 2025-01-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
